# Generated by Django 3.1.5 on 2021-01-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goologin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='blogimg'),
        ),
    ]
